### PR TITLE
Architecture diagram

### PR DESCRIPTION
**Pull request by lukieh2014**
First draft of architecture diagram, before subnets and VPCs, referring to ticket #1 .

### CODE REVIEW

**Comment by lukieh2014** [comment]
missing subnets, region, and VPCs.

**Comment by lukieh2014** [comment]
Also need to add clarification on trend alert system

**Review by ebradley12 — APPROVED** [review]

**Comment by lukieh2014** [comment]
Having discussed with tech coaches, decided to scrap S3 bucket as not necessary. All data will therefore be stored on the RDS.

**Review by ebradley12 — APPROVED** [review]
Great first drift. Very detailed

**Review by bentrzcinski — COMMENTED** [review]
Looks good Luke, happy to approve once you've made the changes you've mentioned. Worth noting that the user will subscribe from the dashboard. Could that be captures in the diagram somehow?

**Comment by lukieh2014** [comment]
Thanks Ben, good idea, just added the user to the diagram.

**Review by emily-curtis — APPROVED** [review]
so detailed, looks great!!

**Comment by ebradley12** [comment]
We decided to change the schema to add an S3 bucket for the pdf buckets so the dashboard can extract from the bucket

**Pull request merged**
