### PR TITLE
Project overview README.md first draft

### PR DESCRIPTION
**Pull request by ebradley12**
#15 - This pull request adds a detailed and structured README file for the Band Camp Tracker Project. The README provides essential information about the project.

### CODE REVIEW

**Comment by lukieh2014** [comment]
looks great! I like the set-up for inserting images of ERD and architecture diagrams.

**Review by lukieh2014 — APPROVED** [review]

**Comment by ebradley12** [comment]
Need to change the test folder structure to include test file in pipeline folder

**Review by GabrielNsiah — APPROVED** [review]
Looks Good!

**Review by emily-curtis — APPROVED** [review]
Great readme, looks good to go! 🤠

**Review by bentrzcinski — APPROVED** [review]
Really nice template

**Pull request merged**
