### PR TITLE
updated architecture diagram

### PR DESCRIPTION
**Pull request by lukieh2014**
Updated architecture diagram. Now has an S3 bucket to store PDF daily summary reports, and dashboard will send out email alerts to users. Referring to ticket #1 .

### CODE REVIEW

**Comment by ebradley12** [comment]
Looks really good. Great idea using an S3 bucket to store PDF reports

**Review by ebradley12 — APPROVED** [review]

**Comment by bentrzcinski** [comment]
Can we make sure all the labels on the arrows have uniform capitalisation?

**Comment by bentrzcinski** [comment]
Is private subnet implicit for everything not in the public subnet or do we need to include this?

**Comment by bentrzcinski** [comment]
Are all the arrows facing the right way to represent flow of data? Is this application uniform across the whole diagram?

**Comment by lukieh2014** [comment]
There aren't any resources in the private subnet for this project: EventBridge schedules and ECRs exist outside of any subnets, and normally the RDS would be in a private subnet. However as the RDS needs to be accessible by the streamlit dash, it also must live in the public subnet.

**Comment by lukieh2014** [comment]
The arrow directions represent which resource is initiating communication with the other, not necessarily the flow of data.

**Comment by bentrzcinski** [comment]
Oh okay cool, I'm assuming the Lambda's do too if they are already outside of the VPC?

**Comment by lukieh2014** [comment]
Yes the Lambdas won't be inside the VPC or any subnet as this can cause complications.

**Review by emily-curtis — APPROVED** [review]
Looks fab!

**Pull request merged**
