### PR TITLE
updated architecture diagram with changes made in resources and design

### PR DESCRIPTION
**Pull request by lukieh2014**
Updated the overall project architecture diagram to display the changes discussed to the project's resources and design, such as splitting the alerts system into it's own Lambda function, and running the pipeline every 10 minutes (instead of 3). Referring to ticket #77 .

### CODE REVIEW

**Review by ebradley12 — APPROVED** [review]
Looks good!

**Review by bentrzcinski — COMMENTED** [review]
The 'Reads image from ECR' arrow points from the ECR to the Lambda, but the 'Reads data from RDS' arrow points from the Lambda to the RDS. If we are following the flow of data with these arrows, are they inconsistent?

**Comment by lukieh2014** [comment]
@bentrzcinski please see the updated diagram, I changed the direction of the arrows pointing to the ECRs to keep the arrows consistent (i.e. the resource initiating communication with the responder).

**Comment by bentrzcinski** [comment]
> @bentrzcinski please see the updated diagram, I changed the direction of the arrows pointing to the ECRs to keep the arrows consistent (i.e. the resource initiating communication with the responder).

**Comment by bentrzcinski** [comment]
Personally I still think It's slightly confusing having the arrows this way round for getting data. I find it hard to reconcile the difference between taking data from the RDS to process it, and pushing the processed data to the S3, when the arrows are the same direction for both. Regardless, as long as we are being consistent!

**Comment by lukieh2014** [comment]
fair point on the pipeline Lambda, I have changed these arrows to be coming from the Lambda now as it is the Lambda initiating communication with the BandCamp website and API.

**Review by bentrzcinski — APPROVED** [review]
Looks good to me!!

**Pull request merged**
