### PR TITLE
60 update erd diagram

### PR DESCRIPTION
**Pull request by emily-curtis**
Added new genre-release table to the erd, and changed bigints to smallint or int.l

### CODE REVIEW

**Comment by ebradley12** [comment]
Looks good - can we just spread the tables out a bit more to ensure the relationships between them are visually clearer and less cramped

**Comment by ebradley12** [comment]
We also need to remove genre_id from the release table

**Review by bentrzcinski — COMMENTED** [review]
The file is suddenly very small?

**Comment by ebradley12** [comment]
I've just noticed country_id is bigint in the customer table but smallint in the country table. Please can we update this :)

**Comment by ebradley12** [comment]
Same with artist_id and type_id and release_id - please can we make sure all the INT types match

**Comment by ebradley12** [comment]
Also, this is picky but can we use underscores for the subscriber_genre and release_genre table names just to match the table names in the schema :)

**Review by ebradley12 — APPROVED** [review]
Perfect!

**Review by lukieh2014 — APPROVED** [review]
nice changes, looks good to me!

**Pull request merged**
